### ISSUE TITLE
Generate reference points for structural engineering design problems

### ISSUE THREAD

**Issue by shdotcom** [rsain/IRA-EMO#1]
Hi,
How to used IRA-EMO to generate reference points, to be used with preference-based multi-objective optimization algorithm, such as , R-NSGA-II, in solving structural engineering design problems, such as, Spring design, welded beam problems and others.
Thank you

**Comment by rsain** [comment]
Hi @shdotcom,

IRA-EMO does not generate reference points. Instead, you should give them (i.e. an aspiration and a reservation level). Then, the desired number of solutions is generated to represent the part of the Pareto  optimal front bounded by the aspiration and the reservation levels given.

Therefore, reference points are not generated by the method but given by the decision maker.

I hope it helps.

Kind regards,
Rubén.

**Comment by shdotcom** [comment]
Thank you fort your reply. 
Is it possible to add another problem with constraints, such as, spring design and welded beam problems?
